const villesDeFrance = [
    { label: 'Paris' },
    { label: 'Marseille' },
    { label: 'Lyon' },
    { label: 'Toulouse' },
    { label: 'Nice' },
    { label: 'Nantes' },
    { label: 'Strasbourg' },
    { label: 'Montpellier' },
    { label: 'Bordeaux' },
    { label: 'Lille' },
    { label: 'Rennes' },
    { label: 'Reims' },
    { label: 'Le Havre' },
    { label: 'Saint-Étienne' },
    { label: 'Toulon' },
    { label: 'Grenoble' },
    { label: 'Dijon' },
    { label: 'Angers' },
    { label: 'Nîmes' },
    { label: 'Villeurbanne' },
    { label: 'Clermont-Ferrand' },
    { label: 'Le Mans' },
    { label: 'Amiens' },
    { label: 'Aix-en-Provence' },
    { label: 'Limoges' },
    { label: 'Tours' },
    { label: 'Metz' },
    { label: 'Perpignan' },
    { label: 'Besançon' },
    { label: 'Boulogne-Billancourt' },
    { label: 'Orléans' },
    { label: 'Rouen' },
    { label: 'Mulhouse' },
    { label: 'Caen' },
    { label: 'Nancy' },
    { label: 'Saint-Denis' },
    { label: 'Saint-Paul' },
    { label: 'Montreuil' },
    { label: 'Avignon' },
    { label: 'Versailles' },
    { label: 'Créteil' },
    { label: 'Poitiers' },
    { label: 'Aulnay-sous-Bois' },
    { label: 'Vitry-sur-Seine' },
    { label: 'Pau' },
    { label: 'Calais' },
    { label: 'La Rochelle' },
    { label: 'Colombes' },
    { label: 'Asnières-sur-Seine' },
    { label: 'Rueil-Malmaison' },
    { label: 'Saint-Maur-des-Fossés' },
    { label: 'Courbevoie' },
    { label: 'Fort-de-France' },
    { label: 'Champigny-sur-Marne' },
    { label: 'Aubervilliers' },
    { label: 'Drancy' },
    { label: 'Maisons-Alfort' },
    { label: 'Neuilly-sur-Seine' },
    { label: 'Narbonne' },
    { label: 'Antony' },
    { label: 'Noisy-le-Grand' },
    { label: 'Sarcelles' },
    { label: 'Niort' },
    { label: 'Bondy' },
    { label: 'Créteil' },
    { label: 'La Seyne-sur-Mer' },
    { label: 'Lorient' },
    { label: 'Carcassonne' }
    // Ajoutez d'autres villes ici si nécessaire
  ];
  
  export default villesDeFrance;
  